version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - logs:/var/www/logs
            - ./app:/var/www/app
            - ./src:/var/www/src

    phpunit:
        build:
            context: .
            dockerfile: Dockerfile.phpunit
        volumes:
            - logs:/var/www/logs
            - ./app:/var/www/app
            - ./src:/var/www/src
            - ./tests:/var/www/tests
        entrypoint: [ "php", "./vendor/bin/phpunit" ]
