# Dockerfile for the phpunit service
FROM php:8-alpine

WORKDIR /var/www

# Install Composer
RUN apk --no-cache add curl \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy your application files
COPY . /var/www

# Install dependencies, including PHPUnit
RUN composer install

# Command to run PHPUnit
CMD ["php", "./vendor/bin/phpunit"]
